### ISSUE TITLE
Time Ontology -small suggestions

### ISSUE THREAD

**Issue by neilotte** [CommonCoreOntology/CommonCoreOntologies#11]
I've been comparing the Time Ontology to the [OWL Time Ontology](https://www.w3.org/TR/owl-time/). Here are some small suggestions for the CCO:

1. There are a few relations in CCO-Time that seem like sub relations of another relation. For instance, 'interval is after' and 'interval is before' are both sub relations of 'interval disjoint'. 

2. I don't see 'Time Zones' represented in the CCO's Time. Is there another way they are being treated? 

3. Is there a place in the CCO for temporal reference systems? 

4. For consistency, why not treat the subclasses of one-dimensional temporal region presently in the CCO (e.g. Day, Decade, Hour, Minute, etc) as instances of temporal units like the measurements of units ontology does for units?

**Comment by bdonohue29** [comment]
1. This is interesting. I think you're correct that before/after are subpropeties of disjoint, considering disjoint is defined in terms of one interval that is "before OR meets" the other. Before/after properties are about intervals which meet, therefore I don't see why they wouldn't qualify as subproperties.

2. At present, time zones are represented in terms of an identifier attached to the IBE which has the datetime information. Specifically, the class "Time Zone Identifier" is in our Information Entity Ontology, and is annotated in part as follows:

"There is no class 'Time Zone' (the region), only 'Time Zone Identifier' (the designator for some region). Instances of 'Time Zone Identifier' should be related to instances of 'Information Bearing Entity' by means of the object properites 'uses time zone identifier' and 'time zone identifier used by' as appropriate..."

The reason is basically that it would be difficult, if not impossible, to represent the relationship between data which references a timezone and the timezone-qua-region. I might have a piece of data which timestamps something as happening at 12:00 GMT, but what's the relationship between the geospatial region delineated as GMT and my data? I can't, for example, presume that the event I'm describing occurs somewhere in that region.

3. Information Entity Ontology also includes "Reference System," including the subclass "Temporal Reference System," which has several subclasses. Again, such reference systems are related to our primary temporal data via the IBE. E.g., our data reads "2018-05-21T12:00:00" and we append to the IBE the fact that the "Solar Calendar System" being used here is the instance "Gregorian Calendar".

4. Because "Day" is not an instance, but a class, of which May 20 and May 21 are instances.

**Comment by bdonohue29** [comment]
P.S. If the "Time Ontology in OWL" isn't called "TOWL," then somebody needs to ask for their money back.

**Comment by neilotte** [comment]
Thanks for the helpful explanations. You might also see in 'TOWL' the relation 'interval in' whose subs include interval during, interval finishes, and interval starts.

Concerning your comment on 'Day', the same could be said of 'inches'. For instance, there is the instance of a measurement unit of length 'inch', but then there's _this_ inch, which is a one-dimensional spatial extent that is measured by the instance of measurement of length 'inch'. Since you don't need to represent both inch-qua-informational-entity and inch-qua-unitized-quantity-kind in your ontology, you only need choose one way of going. And the CCO does exactly this. I was just pointing out that it appears one methodology was used for units of measurement (the former), while the second was used in the Time ontology.

**Comment by bdonohue29** [comment]
There's an ambiguity between designating a day-long 1d temporal interval and measuring a region in units of 1 or more days. Yes, the former is based in some way on the latter. But I wouldn't say there's a redundancy here, for the simple reason that people are in the habit of designating temporal regions (e.g., "May 21, 2018), but not of measuring the interval from 0 C.E. to present using measuring units.

**Comment by APCox** [comment]
The object properties interval_meets, interval_met_by, interval_is_before, and interval_is_after are now all sub-properties of interval_disjoint.
