### ISSUE TITLE
'has date value' missing range xsd:date

### ISSUE THREAD

**Issue by alanruttenberg** [CommonCoreOntology/CommonCoreOntologies#117]
The other 'has xxx value' properties, other than 'has altitude value' have appropriate ranges. For altitude, the other two components, lat and long, have ranges xsd:decimal, so perhaps altitude should also?

Lat and Long can be more tightly specified using a datarange. To add these in Protege, choose the datarange tab and enter something like this:  xsd:decimal[>= -90 , <= 90]

I didn't remember the syntax but found it in [this stackoverflow answer](https://stackoverflow.com/questions/24531940/defining-datarange-expression-in-protege-for-a-data-type-property)

**Comment by APCox** [comment]
If I recall correctly, there is an issue with xsd:date not being supported in OWL. This page supports this: (https://www.w3.org/2011/rdf-wg/wiki/XSD_Datatypes). This has been a minor annoyance to us for a while now and we previously removed references to xsd:date because it was causing errors.

Regarding the declaration of a value range restriction for Lat and Long, we also previously removed a number of similar declarations because they caused problems for at least some reasoners. Note, this was a problem with the reasoners, not the axioms.

Adding xsd:decimal to the range for has_altitude_value is a good idea.

**Comment by alanruttenberg** [comment]
Thanks, I forgot about xsd:date and OWL issue. We might consider establishing a convention to use xsd:dateTime with time set to beginning of day, but it's not ideal. Which is lesser of evils - no domain, or kludge?

Curious: Which reasoner had problems with the datarange facets?  

One approach for dealing with issues like this is to separated out certain types of axioms such as these into a separate import. Then, for reasoning purposes create two, reasoner-specific OWL files, one which imports the dataranges and other reasoner-unsupported axioms and one that doesn't

**Comment by cameronmore** [comment]
As noted, xsd:date is not covered, and the discussion of data type properties is tied in with the value specification proposal
