### ISSUE TITLE
has organizational context

### ISSUE THREAD

**Issue by JNeilOtte** [CommonCoreOntology/CommonCoreOntologies#15]
I don't see that the domain and range of this relation are set, but I'm assuming they hold between roles and organizations. 

This being the case, it would also be helpful to see a similar relation for those roles that are realized in belonging to a group that is not an organization. For instance, a protester role 'has group context' some protest group.

**Comment by rorudn** [comment]
I'm not convinced that being a protestor, passenger, bystander, audience member, New Yorker or the like are roles. Rather they are defined classes of persons participating in certain kinds of activities, protesting, traveling by vehicle, watching a performance or living in New York. I hesitate to add such a relation as 'has group context' for fear of encouraging the over use of roles.

**Comment by neilotte** [comment]
For many of these, the interpretation of the 'participates in' and 'agent in' relation is too broad to serve as defined classes. A civilian can be a participant in an act of protest, but is not a protester. It also seems a police officer can even be an 'agent in' an act of protest, but is not a protester.

**Comment by rorudn** [comment]
Only if you equate an act of protest with a protest. For the most part the acts that are classified in the Common Core are actions performed by an individual but it is true that there are exceptions including such as election, wedding, act of manufacturing. Nonetheless a protester should still be defined as a person that is agent in an act of protest. A bystander should still be defined as a person that is agent in an act of observation. A police officer has a role that has the organizational context of the police department that he or she is part of and which is realized in an act of public safety. The act of protest, the act of observation and the act of public safety should all be process parts of a protest.

**Comment by APCox** [comment]
As Ron stated, we can represent who participated in what capacity in any given event without creating a role for each mode of participation. The preferred CCO approach is to represent the _events_ in greater detail.

Consider a wedding in which 100 people participate in one or more capacities. Let's say you want to know who got married, who officiated, who acted as legal witnesses, who the photographer was, etc. etc. etc., as well as who merely attended the wedding as guests. 

You _could_ do this by creating new roles, assigning instances of them to each participant, and asserting that these roles get realized in the single instance of 'Wedding'. This will allow you to answer the above questions regarding in what capacity each person participated in the wedding. You will not, however, be able to answer more in-depth questions regarding each person's participation (such as when and where they were participants or how well they performed their part).

The CCO approach would represent the wedding along the following lines (note that this is for illustrative purposes only):

There is a Wedding process that has 100 participants and also has many process parts. The Wedding has process part an ActOfMarrying, which causes a Married stasis that has as participants only the 2 people who got married. The officiant is the agent in an act of solemnizing, which is a process part of the ActOfMarrying. (NB: the officiant _does_ have an officiant role since the authority to officiate weddings is granted by a formal organization, so we could instead say that the officiant is the person who's officiant role is realized by the ActOfMarrying.) The legal witnesses are those persons who were agents in an ActOfOfficialDocumentation that had object the wedding license (and who were neither the officiant nor one of the married persons, since those people will also need to sign the license). Many people probably took photos at some point during the Wedding, but only the wedding photographer was doing so in fulfillment of a Contract with the newly weds. The same goes for the hired DJ, band, caterer, etc. whose participation may each be further represented by the types of services they perform. Employees of these service providers, e.g. the assistant photographer and the waitstaff, can be identified by their participation in instances of ActOfEmployment that are connected to their employers and are realized (at least partially) in the same time and place as the Wedding. A similar story can be told for each participant in the Wedding. Finally, wedding guests will be those people who participated in the wedding, but did not do so in any of the specified ways would make them non-guest participants. No roles were needed to accomplish this.
