### ISSUE TITLE
Minor labeling comment

### ISSUE THREAD

**Issue by dlutz2** [CommonCoreOntology/CommonCoreOntologies#16]
Noticed that 5 CC Annotation properties use the same label as a OBO Annotation property:

- cco:definition - obo:IAO_0000115
- cco:definition_source - obo:IAO_0000119
- cco:elucidation -  obo:IAO_0000600
- cco:example_of_usage - obo:IAO_0000112
- cco:term_editor - obo:IAO_0000117

cco:Skill (in AgentOntology) uses obo:IAO_0000115 instead of (?) cco:definition

Wasn't clear if these properties are meant as distinct concepts from their IAO counterparts.

Similarly, the Lewisian relations all have the same label as their non-Lewisian counterparts.

This was flagged in our OWL verbalizer code which looks for 2 or more entities in the import closure with the same label.

**Comment by mark-jensen** [comment]
Thanks for the catch re use of the IAO property vs. the CCO one in cco:Skill. Will fix for next release.

CCO uses term identifiers composed of meaningful text that match the term label. An early decision was made to use our own annotation properties that mirror the IAO ones. This provides a layer of usability in certain applications where it   ##is helpful to quickly know what a IRI refers to without having to query for its label. The IAO properties appear in CCO because we import BFO, but CCO does not use IAO. BFO doesn't actually import IAO, those few properties are directly added (ie- declared) in BFO.

We should probably acknowledge the overlap, perhaps add an external reference or even an equivalency axiom.

**Comment by dlutz2** [comment]
A couple more pedantic labeling/annotation things:
cco:ImprovisedExplosiveDevice and cco:LandMine have "alternative label" value pointing to Wikipedia, probably meant as definition_source ?

cco:Infrastructure is missing label/alternative label

I found the labels on two of the multi X temporal intervals confusing, different pattern from the others: 
cco:MultiSecondTemporalInterval  labeled as "part of Minute"  could be Multi-Second Temporal Interval
cco:MultiMinuteTemporalInterval  labeled as  "part of Hour"  could be Multi-Minute Temporal Interval  
 These labels sounded like "an interval of less than an X" to me 

Spelling
cco:Cubiod - Cubiod
cco:ReflectingOpticalTelescope  - Refelector
cco:DegreeFahrenheitMeasurementUnit - Degree Fahhrenheit Measurement Unit
cco:IntrasonicFrequency - Intrasonic Frequency
cco:SecondaryCellElectricBattery - Rechargable Battery

Really pedantic
There were also a couple of Properties which didn't follow the "is VERBed by" or 'is/has NOUN PREP"
patterns used elsewhere (missing the is/has part). Can supply if of use.

Sorry if this is too picky to be useful. It showed up as part of our natural language work.

**Comment by dlutz2** [comment]
Look like passives, should likely have pattern "is verbed by"
- caused_by
- described_by
- designated_by
- prescribed_by
- realized_by
- represented_by
- time_zone_identifier_used_by

some noun prep combos could be either " is noun prep" or "has noun prep" depending on intent
- accessory_in
- accomplice_in
- aggregrate_bearer_of
- bearer_of
- capability_of
- capability_of_aggregate
- connected_with
- disconnected_with
- disposition_of
- disposition_of_aggregate
- example_of_usage
- function_of
- language_used_in
- nontangential_proper_part_of
- quality_of
- quality_of_aggregate
- realizable_entity_of
- role_of
- role_of_aggregate
- spatial_part_of
- spatial_proper_part_of
- tangential_proper_part_of

 thanks
