### ISSUE TITLE
Do Planned Acts need to be prescribed by some Plan?

### ISSUE THREAD

**Issue by nklsbckmnn** [CommonCoreOntology/CommonCoreOntologies#172]
Currently, Planned Acts are defined as „An Act in which at least one Agent plays a causative role and which is prescribed by some Directive Information Content Entity held by at least one of the Agents“. Unplanned Acts are defined as „An Act in which at least one Agent plays a causative role and which is not prescribed by some Objective held by any of the Agents“.

Is it on purpose that Planned Acts are not defined by being prescribed by Plans or requiring Objectives? 

The current definitions make Planned Acts and Unplanned Acts non-disjunctive because Directive ICEs do not require Objectives. They make Planned Acts compatible with teleological theories of action while remaining compatible with causal theories of action. But they are not compatible with causal theories of action that do not assume Objectives.

**Comment by avsculley** [comment]
I will assess the claim that planned/intentional acts should not require an objective. First, let me present the definitions at issue here.

> cco:Objective "A Directive Information Content Entity that prescribes some projected state that some Agent intends to achieve."
> 
> cco:IntentionalAct "An Act in which at least one Agent plays a causative role and which is prescribed by some Directive Information Content Entity held by at least one of the Agents."
> 
> cco:Plan "A Directive Information Content Entity that prescribes some set of intended Intentional Acts through which some Agent expects to achieve some Objective."



Here is the relevant portion of the wikipedia article on general intent/basic intent:


> Offences requiring basic intent specify a mens rea element that is no more than the intentional or reckless commission of the actus reus. The actor either knew (intended) or deliberately closed his mind to the risk (recklessness) that his action (actus reus) would result in the harm suffered by the victim. The crime of battery, for example, only requires the basic intent that the actor knew or should have known that his action would lead to harmful contact with the victim.


The claim might be something like the following. The batterer, B, need not knowingly/intentionally punch their victim, V, and thus harm V. It might be that B & V are both dancing at a bar and dancing in close quarters. B might like doing the fist pump. If B makes sufficient contact with V, it counts as battery becasue it is clearly reckless to fistpump in close quarters. In other words, B should have known that a fist pump would lead to harmful contact with V. In this case, it seems B has no objective with respect to harming V.

The question is, in his fist pumping, does B lack a cco:Objective? B seems to have the objective to punch his hand in the air (over and over again). It is a projected state that B intends to achieve. If so, then it is a cco:plannedAct.

Of course, B's objective is not to punch V, but this need not count against cco's ability to account for the criminal domain. Instead it shows that the criminal justice system labels some cco:plannedActs as unplanned becasue they lack the kinds of objective that matter to the criminal justice system. A reckless action is (something like) a planned action whose objective(s) are not achieved cautiously.

I look forward to any counterexamples that might escape a similar explanation.

**Comment by cameronmore** [comment]
[Issue 155](https://github.com/CommonCoreOntology/CommonCoreOntologies/issues/155) discusses the potential of adding objectives. I think it's reasonable to add, and I would add to this conversation that it depends what kinds of inferences you want the ontology to make, which is a reflection of what the _data_ does and doesn't contain.

Not every planned act needs a Directive ICE, but if one wants to specify how the action is being carried out, the Directive ICE can be used. Generally, Planned Acts involve agents, that there is some causative and intentional heft going on, which is true of crimes even if criminals don't have a step-by-step plan written out.

CCO has taken a stance on agency, and the planned acts reflect that, but open to compelling discussion.
