### ISSUE TITLE
Documentation for has-participant properties in bfo2020 branch

### ISSUE THREAD

**Issue by swartik** [CommonCoreOntology/CommonCoreOntologies#185]
On branch bfo2020, the skos:definition annotation for property BFO_0000057 (has participant at some time) reads:

     p has participant c at some time =Def for some time t (b is a process, c is a continuant, and c participates in p some way at t

Should it read "**_p_** is a process"? BFO_0000167 (has participant at all times) has analogous wording.

This may be an issue for BFO rather than CCO, but I've searched the github site for BFO and didn't find a file with this annotation. So, not knowing how bfo-2020.owl was obtained, and whether it underwent transformation in the process, I report the issue here, in hopes someone will report it to "the proper authorities." Apologies for any extra work caused.

**Comment by johnbeve** [comment]
@mark-jensen @APCox @cameronmore Correct me if I'm wrong, but I believe this issue is OBE given the [upcoming release](https://github.com/CommonCoreOntology/CommonCoreOntologies/tree/build-new-version-1.5) and the [bfocore branch](https://github.com/CommonCoreOntology/CommonCoreOntologies/tree/bfo2020-core).

**Comment by mark-jensen** [comment]
@johnbeve Agreed. Very OBE. @swartik Closing this, handled elsewhere.
