### ISSUE TITLE
Discrepancy between definition and axioms for 'Agent' class

### ISSUE THREAD

**Issue by pfabry** [CommonCoreOntology/CommonCoreOntologies#186]
Agent is currently defined as: "A Material Entity that is capable of performing Planned Acts". However, the current axioms state:  `Agent EquivalentTo 'material entity' and ('agent in' some process)`

This axiom implies that an agent is causally active in a process, not merely capable of performing it. 

Could an axiom using `agent capability` be a better fit?

**Comment by neilotte** [comment]
@pfabry This makes sense to me. Good eye.

**Comment by neilotte** [comment]
@mark-jensen  This seems like low-hanging fruit for 1.7. Update axiom to: 

Agent EquivalentTo 'material entity' and ('bearer of' some 'agent capability')

Sound good?

**Comment by cameronmore** [comment]
Should the definition be updated as well? @neilotte 
`Agent = A Material Entity that bears an Agent Capability.`
The current definition of Agent Capability is `A Realizable Entity that inheres in an Agent to the extent of that Agent's capacity to realize it in Intentional Acts of a certain type.`
Since Agent Capability references Agent in its definition, should we change that as well to Material Entity?

**Comment by mark-jensen** [comment]
closed with #532

**Comment by mark-jensen** [comment]
Fixed with #532
