### ISSUE TITLE
Definition of relational quality in bfo2020 branch

### ISSUE THREAD

**Issue by swartik** [CommonCoreOntology/CommonCoreOntologies#189]
The definition of BFO class BFO_0000145 (relational quality) is:

     b is a relational quality =Def b is a quality and there exists c and d such that b and c are not identical,
     & b s-depends on c & b s-depends on d

Should it state that c and d, rather than b and c, are not identical?

I looked at the BFO website. It has a different definition (on the BFO2.0 branch):

    b is a relational quality = Def. for some independent continuants c, d and for some time t:
    b quality_of c at t & b quality_of d at t.

Because this definition requires c and d to be independent continuants, it seems to conflict with the definition in the CCO version of BFO.

**Comment by alanruttenberg** [comment]
BFO-2020 dropped the quality_of, function_of etc relations that were subproperties of inheres_in to simplify and since those properties are easily defined outside BFO-2020.

s-depends is transitive. Any specifically dependent continuant(SDC) that s-depends on something eventually also s-depends on some  independent continuant that's not a spatial region (ICnoSR).  

From BFO 2.0
```
b quality_of c at t = Def. b is a quality & c is an independent continuant that is not a spatial region & b s-depends_on c at t. [056-002]
```
The bottom line is that the old definition lands up being equivalent the new definition

So suppose you have the following,

1. sdc1 instance-of quality
2. sdc2 instance-of quality
3. sdc1 s-depends-on sdc2
4. sdc2 s-depends-on ic1

implications:
5. sdc1 s-depends on ic1 (by transitivity 3 and 4)
6. sdc1 quality_of ic1 (by definition of quality_of and 1, 5)
7. sdc2 quality_of ic1 (by definition of quality_of and 2, 4)
8. sdc1 instance_of relational quality (by either definition. BFO-2020 uses 4, 5, BFO2.0 by 6, 7)

Note that 6,7 will not be inferred by OWL but would be inferred in
the BFO-2020 axiomatization, if the definition of quality_of was added.
8 will be inferred by BFO-2020 regardless. None of 6, 7, 8 will be inferred
by OWL, since the OWL is weaker than the FOL.

The old definition implies the new definition, since quality_of is a
subproperty of inheres_in which is a subproperty of s-depends-on.  So
relational qualities will be relational qualities by either definition.

**Comment by mark-jensen** [comment]
>Because this definition requires c and d to be independent continuants, it seems to conflict with the definition in the CCO version of BFO.

@swartik You are correct. The BFO2020 branch was created to experiment with alignng CCO with BFO2020. It has not been updated in quite a while and the version of BFO located there is now out of sync with recent changes to BFO2020. With recent activities in development and curation of CCO and BFO, I expect there be many changes coming soon. Stay tuned!

**Comment by swartik** [comment]
@mark-jensen I am waiting with bated breath. If you need a reviewer, I'll try to make room in my schedule.

**Comment by mark-jensen** [comment]
@swartik Will add you to the PR, but as you know, it is different branch now: [bfo2020-core](https://github.com/CommonCoreOntology/CommonCoreOntologies/tree/bfo2020-core)
