### ISSUE TITLE
Comments from Brian Haugh from motion to Approve CCO v1.4 as Working Document

### ISSUE THREAD

**Issue by jimschoening1** [CommonCoreOntology/CommonCoreOntologies#196]
Brian Haugh Comments: I question the suitability of formulating the CCO in a single MergedAllCoreOntology Turtle (.ttl) file since the previous formulations in separate ontology files facilitate more selective reuse of just those parts of CCO that a particular application may need. In particular, it seems inadvisable to merge BFO into the CCO, but better to import it. 
There is also a question of whether to use Turtle, RDF/XML, or other serializations of the CCO for the reference version.  I believe that the DIOWG guidance is leaning towards requiring RDF/XML for ontologies in its Foundry.

**Comment by BrianHaugh** [comment]
It seems that we have some agreement from Alan Ruttenberg and Mark Jensen that BFO is best excluded from any merged file of CCO ontologies. We also seem to agree that there can be multiple serializations of the CCO, e.g, in Turtle or RDF/XML.  I recommend including an RDF/XML version on the IEEE site so that it is available for inclusion in the DoD/IC Ontology Foundry, which I understand to be requiring ontologies to be serialized in RDF/XML. 
I propose that the IEEE standard for CCO continue to maintain separate files for its component ontologies and import statements to merge them.  A merged file could also be maintained as part of the standard.
