### ISSUE TITLE
is subProperty of a SymmetricProperty also symmetric?

### ISSUE THREAD

**Issue by ramesh-gupta** [CommonCoreOntology/CommonCoreOntologies#197]
cco:is_spouse_of rdf:type owl:SymmetricProperty .
cco:has_wife rdfs:subPropertyOf cco:is_spouse_of .

ex:john cco:is_spouse_of ex:mary . 
# => ex:mary cco:is_spouse_of ex:john .

ex:john cco:has_wife ex:mary . 
# That should not entail ex:mary cco:has_wife ex:john .

Does it or doesn't it, and why? Is this a problem in the ontology or is this a misunderstanding on my part? This is a very basic question, and I suspect it is the latter. So I apologize in advance :-)

Thanks

**Comment by johnbeve** [comment]
The role constraints of parent properties are not - in general - inherited by sub-properties. 

- R rdfs:subPropertyOf R* means that if R(x,y) then R*(x,y)).
- R* owl:SymmetricProperty means that if R*(x,y) then R*(y,x).
- But these together do not entail that if R(x,y) then R(y,x). 

Using a version of your example to illustrate: 
1. Suppose the extension of property **is_spouse_of** is the set {<john,mary>}. 
2. Suppose the extension of property **has_wife** is the set {<frank,sally>}. 
3. If we assert **has_wife** owl:subPropertyOf **is_spouse_of**, the extension of **is_spouse_of** becomes  {<john,mary>,<frank,sally>}.
4. If we then assert **is_spouse_of** rdf:type owl:SymmetricProperty, then the extension of **is_spouse_of** becomes {<john,mary>, <mary,john>, <frank,sally>, <sally,frank>}, i.e. mary **is_spouse_of** john.
5. But the extension of **has_wife** remains {<frank,sally>}.
6. Moreover, if we expand the extension of **has_wife** to  {<john,mary>, <frank,sally>}, it would not follow that mary **has_wife** john, since nothing requires including <mary,john> in the extension of **has_wife**.

**Comment by ramesh-gupta** [comment]
Thank you so much for the clarification!
