### ISSUE TITLE
OWL file for Modal Relation Ontology

### ISSUE THREAD

**Issue by gregfowlerphd** [CommonCoreOntology/CommonCoreOntologies#240]
Perhaps I'm making some kind of error (either in my usage of Protege or in my understanding of what the Modal Relation Ontology is supposed to be), but there appears to be a problem with the OWL file for that ontology. In the Object properties tab, Modal Object Property has a number of subproperties, but all of them appear to be properties from other CCO ontologies and none appears to be a _modal_ relation.

**Comment by swartik** [comment]
@gregfowlerphd, what view setting are you using (`View -> Render by` menu items)? If you're using rdfs:label, know that Protege does not handle well situations where two properties have the same label. Because the modal relation properties have identical labels to their non-modal equivalents, it's easy to be confused by Protege's display.

Switch to `View -> Render by prefixed name` and Protege should show the distinction clearly.

**Comment by cameronmore** [comment]
You may be seeing that the rdfs:labels are the same as the regular relations, but beneath, the IRIs are different.

**Comment by cameronmore** [comment]
That is, they are all modal versions of the other ontologies, and they have the exact same label. If you look at the IRI on the right hand side above the annotations, you should see that is has ModalRelationOntology there.

**Comment by gregfowlerphd** [comment]
@swartik and @cameronmore:

Thanks you two! I now see that although the rdfs:labels of the Modal Relation Ontology's object properties are the same as those of properties from the other ontologies, the IRIs are different.

While I haven't checked them all, from those I have checked, it also looks like the definitions are the same. Is that right?

Also, is there any unique content in the Modal Relation Ontology other than the different IRIs for the object properties?

**Comment by cameronmore** [comment]
No problem

Not really, it's a minimal change of the properties so you can model a fictitious world in the same way as you would model the real world.
