### ISSUE TITLE
Definition of ‘Mine’ too restrictive?

### ISSUE THREAD

**Issue by gregfowlerphd** [CommonCoreOntology/CommonCoreOntologies#281]
According to the definition, to be a mine, a facility must be designed to support the extraction of valuable minerals _and_ geological materials from the earth. This immediately raises the question: Are minerals themselves considered to be geological materials?

If not, the definition may be too restrictive, since it would not count a facility that is designed to support _only_ the extraction of valuable minerals (and not also of geological materials) as a mine. In that case, perhaps the ‘and’ should be changed to ‘and/or’.

If so, then perhaps ‘valuable minerals and geological materials’ should be changed to ‘geological materials, such as valuable minerals’ or ‘valuable minerals and/or other geological materials’.

Additionally, I worry about the presence of ‘valuable’ and ‘which forms the mineralized package of economic interest to the miner’. Presumably, one could (for example) set up a practice mine that is not intended to extract anything valuable or of any economic interest.

**Comment by swartik** [comment]
Presumably, one could (for example) set up a practice mine that is not intended
    to extract anything valuable or of any economic interest.

There is (or was – I haven't been in it since the 1970's) such a mine at Penn State University, used to educate students in the College of Earth and Mineral Sciences.

**Comment by cameronmore** [comment]
I think removing 'valuable' and shifting to 'and/or' makes the most sense for a 'quick fix'.

**Comment by gregfowlerphd** [comment]
@cameronmore: When you say "removing 'valuable'", do you mean removing only that word or also the 'economic interest' phrase? It's not clear to me that there's much point in removing the former without removing the latter, though I might be mistaken.

I am inclined to think that if 'and' were changed to 'and/or' and both 'valuable' and the 'economic interest' phrase were removed, the definition would probably be fine.

**Comment by cameronmore** [comment]
@gregfowlerphd so removing 'economic', but leaving interest. There is some theory of interest in the common core--the 'interest in' relation and it's use in the design pattern for disrupting disposition and vulnerability--so leaving that seems fine.

Could 'and/or' be swapped with 'or other'?

The definition becomes:

Mine = A Facility that is designed to support the extraction of minerals or other geological materials from the earth from an orebody, lode, vein, seam, reef, or placer deposits which forms the mineralized package of interest to the miner.

**Comment by gregfowlerphd** [comment]
@cameronmore: One minor issue. 'placer deposits' should maybe be changed to 'placer deposit'. This would make it more grammatically consistent with 'an', 'forms', and 'the mineralized package'. Otherwise, I think the revised definition seems fine.

**Comment by swartik** [comment]
There's [an article in today's NYT](https://www.nytimes.com/2024/06/24/magazine/earth-geomicrobiology-microbes.html?searchResultPosition=2) that relates to this discussion. The Homestake Mine, which operated for over a century, has been turned into a laboratory for physicists and biologists.

Let's say I created an individual in 2000, when the mine was still operating. (Let's also say I had the foresight to predict the emergence of OWL, BFO, and CCO – bear with me.) I asserted this individual to be of type cco:Mine. Fast forward to 2024. The tunnels of the mine still exist, but it's not a mine anymore according to the proposed definitions.

What's the correct approach to modeling this entity? I can see:

1. Assert a new type for the individual and remove the old type.
2. Create a new individual and assert its type to be Facility or a Facility subclass.

If there was a way to temporalize type assertions, I'd go with the first approach. Failing that, I'd use the second approach. I could use processes to describe when the mine individual ceased to be and the research facility began. I'd want to establish some connection saying that the research facility individual is related to the mine individual. Obviously they share the same location. Is there something more specific?

Thoughts?

**Comment by cameronmore** [comment]
That's a great case to work through.

My first thought is that 'capability' would be a great fit. Capability being a disposition that some organism (or group of agents in this case) has an interest in--[arxiv paper here](https://arxiv.org/abs/2405.00183). The individual now gains a cco:ResearchCapability, or some better class maybe--though remains the same instance.

If the facility underwent some remodeling process that changed its affordances, like removed the mining equipment or filled in the shaft with material, I think there would be a good argumentto say that it no longer is of type Mine, since the same physical space underwent such a redesign (artifacts being defined by their designed functions, not their 'real-world uses'). Should the individual be terminated and a new one be created? Not confident, but in the case of such a remodel, I would say yes. (I'm reminded though of laws around historic or old buildings which do not have to keep pace with newer building codes, so construction companies will preserve a very small amount of an old structure, maybe not even a load bearing portion).

Also, this case seems to drive at the fact that the 'building', or basic Facility-ness, remained while its function--of maybe just what it's used for--changed (which has me thinking about businesses that are created with the sole intent to launder money). Given the term capability, I think it would remain a cco:Mine but change in capability, namely, just gain a new type.

I don't know if I answered anything but those are some thoughts

**Comment by swartik** [comment]
I can see a facility constructed as a mine remaining a cco:Mine forever, even if repurposed into a research facility. It still looks like a mine, and I think anyone who went in it would recognize it as such. I'm not so sure that principle works everywhere. The building that was constructed by Justinian I as the Cathedral of Constantinople is now the Hagia Sophia. Typing an individual as both a cco:Church and a cco:Mosque seems fundamentally wrong.

Just food for thought. This is all because of a limitation in OWL, and I hope we can reach agreement on how to accommodate it.

**Comment by cameronmore** [comment]
Lots of good stuff to think through.

Removing the economic implications from the definition is the right thing to do here in any event.

Mine = A Facility that is designed to support the extraction of minerals or other geological materials from the earth from an orebody, lode, vein, seam, reef, or placer deposit which forms the mineralized package of interest to the miner.

**Comment by neilotte** [comment]
An update has been merged into development from this issue. Closing.
