### ISSUE TITLE
File Formats

### ISSUE THREAD

**Issue by neilotte** [CommonCoreOntology/CommonCoreOntologies#29]
Does CCO have a best practice when it comes to tracking the same software file in different formats? For instance, the same report in .txt. or .pdf, or the same image in .png or .jpeg? I don't see this issue mentioned in the modeling information with cco document.

**Comment by swartik** [comment]
It's not in the Best Practices document, but I think _Modeling Information with the Common Core Ontologies_  offers guidance. See Section 2.1. The general idea is that you have:
- A single Information Content Entity that denotes a report's information. 
- Multiple  Information Bearing Entities that all bear said ICE. 

Ideally (getting on my soapbox for a moment), the IBEs are live URLs that, when fed into your web browser, don't yield a 404 error. That way, anyone who accesses them can verify the information content.

**Comment by mark-jensen** [comment]
In CCO, we consider the file format, designated by extensions such as .jpg or .txt, as directive information that prescribes how ICE is encoded digitally. The term `file format` is not yet in the public release of CCO. If you have a need for it, we can discuss adding it.

**Comment by swartik** [comment]
Mark, you wrote "prescribes how ICE is encoded digitally".  To me, the word "how" implies the need to have a process entity, the output of which is an IBE. Am I being too literal? I guess the more concrete question I should ask is the set of individuals and property assertions you envision as necessary to relate an IBE, and ICE, and its format.

**Comment by neilotte** [comment]
Thanks Mark. So 'file format' is a subclass of directive. Then .jpg is a particular, and it bears a 'prescribes' relation to what: a process of digital encoding, or the software file, or the IBE in which the software file inheres?

**Comment by APCox** [comment]
Neil, yes, 'File Format' is a directive that has instances that prescribe instances of 'Digital File', which is an 'Information Bearing Artifact'. If you want/need to explicitly represent the process of implementing the format for a file, you may. Otherwise, it should be sufficient to state that the format instance prescribes the file instance, which bears the ICE instance.

The approach here is the same as what we use for languages, whether natural or artificial. For example, you might add 'American English' and 'British English' as instances of 'Natural Language' then use them to prescribe instances of IBE whose literal values are, respectively:

     American: "Sally removed the large tray of cookies from the trunk of her car, traveled by foot across the parking lot, then took the elevator to her apartment."
     British: "Sally removed the large tray of biscuits from the boot of her car, travelled by foot across the car park, then took the lift to her flat."

Both IBEs might bear the exact same content, but are distinguishable (in part) by the language used to encode this content. As with digital files, it is my opinion that there is only a need to explicitly represent the encoding process if it is important, e.g. when a book is translated from one language to another or an image is converted from one format to another.

**Comment by neilotte** [comment]
Thanks Alex. This issue can probably be closed. Just one last note (probably a second issue) is that the bearer vs. GDC distinction is a general headache on my end. I understand the CCO approach, but enforcing it is difficult. At times too, BFO could be clearer on this. For GDC, for instance, it gives the following example: "the pdf file on your laptop, the pdf file that is a copy thereof on my laptop {@en}"
