### ISSUE TITLE
System Role definition and 'arrangement of parts or elements'

### ISSUE THREAD

**Issue by gregfowlerphd** [CommonCoreOntology/CommonCoreOntologies#302]
According to the definition, a system role inheres in an entity only if that entity is ‘an arrangement of parts or elements’. This doesn’t seem correct (or, at least, is a non-perspicuous way of putting things). Presumably material entities are supposed to be capable of having system roles. But no material entity is an arrangement, since the latter (it would appear) is a certain complex feature a plurality of entities have in virtue of the relations between them.

A better formulation of the definition, I think, would be something like the following:

> A Role that inheres in an entity in virtue of its parts or elements being arranged in such a way that they together exhibit behavior or meaning that they do not exhibit individually.

**Comment by cameronmore** [comment]
There are a lot of views on systems, and I want to just offer one example I brought up in another issue:

Material entities need not be bfo:Objects, that is, unified continuous portions of material (causal unity). One of my favorite examples of a complex material entity is a pair of ear buds which form a single Material Artifact, but may be composed of three objects--the two buds and a case. Rather than assert Object Aggregates everywhere (like Material Artifact Aggregate), I think it's pretty common to leave it understood that Artifacts and other subclasses of Material Entity (not Objects) need not be continuous. Is this a good solution? It works at least, without duplicating the hierarchy everywhere with new types of aggregates.

So, the Earbud Artifact is an arrangement or aggregate, and seems to be "an arrangement of parts or elements that together exhibit behavior or meaning that the individual constituents do not" (supposing that the Earbud Artifact has continuant part one single Bud).

Also, Barry Smith has a relevant paper on [agglomerations](https://philpapers.org/archive/SMIA-2.PDF)

**Comment by gregfowlerphd** [comment]
@cameronmore: Sorry to take awhile to respond. It's been a busy few days. (Birthday and work.)

Thanks for linking to Barry's paper. I'm sure it will be interesting.

So I think we might be talking past each other to some extent. For one thing, while I'm aware that systems are a somewhat fraught topic, my criticism of the System Role definition isn't primarily about systems. It's about "arrangements". (Though I suppose it might have unwanted implications concerning systems?) For another, it doesn't rely on the assumption that material entities need to be bfo:Objects. It applies equally to cases involving Object Aggregates.

Suppose one asks: 'What is the arrangement of the deck chairs?' 'the deck chairs' here might be taken to refer to an object aggregate. However, the question asks after a _property_ or _feature_ of this object aggregate, one that involves the spatial relations between its member parts. Since material entities (including aggregates) aren't properties/features, no material entity is an arrangement.

Thus I deny the interchangeability between 'arrangement' and 'aggregate' you suggest with the phrase 'arrangement or aggregate'. (And I similarly deny that an earbud artifact is 'an arrangement of parts or elements'. It's an aggregate of parts/elements, but not an arrangement.) Notice that if these terms were genuinely interchangeable, then 'What is the arrangement of the deck chairs?' would be equivalent to 'What is the aggregate of the deck chairs?'. But the latter clearly isn't equivalent to the former: It asks after no property or feature of the deck chairs, whereas the former does.

**Comment by gregfowlerphd** [comment]
@cameronmore: Here's another thought about your suggestion that 'arrangement' in the current definition for System Role is interchangeable with 'aggregate'.

If that were so, then the current definition

> A Role that inheres in an entity in virtue of it being an arrangement of parts or elements that together exhibit behavior or meaning that the individual constituents do not.

would be equivalent to

> A Role that inheres in an entity in virtue of it being an aggregate of parts or elements that together exhibit behavior or meaning that the individual constituents do not.

But the latter, allegedly equivalent, definition lacks something the former has. In particular, the former indicates that it is _because of how they are arranged_ that the parts or elements together exhibit behavior or meaning that the individual constituents do not. (And I believe it was the intent of the definition's authors that it indicate this.) However, the latter doesn't indicate this, and hence isn't equivalent to the former.

Notice that my suggested revised definition captures this aspect of the current definition (while also making it more explicit).

**Comment by cameronmore** [comment]
@gregfowlerphd thinking more, your definition makes sense, and I was mistaken about the equivalence of arrangement and aggregate. Does the following still reflect a good definition:

`A Role that inheres in an entity in virtue of its parts or elements being arranged in such a way that they together exhibit behavior or meaning that they do not exhibit individually.`

**Comment by gregfowlerphd** [comment]
@cameronmore: Yeah, I think that definition still works.
