### ISSUE TITLE
Minor issue with definition of ‘Geospatial Ellipse’

### ISSUE THREAD

**Issue by gregfowlerphd** [CommonCoreOntology/CommonCoreOntologies#311]
The definition begins with ‘A Geospatial Boundary that is’. However, since geospatial ellipse is a child class of geospatial line string and only an indirect subclass of geospatial boundary, it should instead start with ‘A Geospatial Line String that is’.

**Comment by alanruttenberg** [comment]
Hadn't seen this issue before, but it looks wrong to be subclass of geospatial line string.  Caught my attention because of commit 175009cf60713b4e4c4c758f04671a2e70bf1508.  An ellipse has no straight lines.
Also, the grandparent label is too broad. It should be something like one dimensional geospatial boundary, since the label geospatial boundary could equall be applied to a surface, such as that delimiting air rights.

**Comment by cameronmore** [comment]
I adjusted the label of the grand parent, reclassed ellipse, and adjusted other definitions that were not in proper genus-species format in this same part of the hierarchy.
