### ISSUE TITLE
Lack of context in, and other problems with, ‘Fuel Artifact Function’ definition

### ISSUE THREAD

**Issue by gregfowlerphd** [CommonCoreOntology/CommonCoreOntologies#313]
The definition reads:

> An Artifact Function that is realized in processes of reacting with other substances in order to release chemical or nuclear energy as heat or ot be used for work.

In the definition, the phrase ‘other substances’ appears out of the blue, given that no substances were mentioned earlier in the definition. Also, later in the definition, ‘to’ is misspelled as ‘ot’. Finally, it’s not entirely clear what’s ‘to be used for work’. (Is it chemical or nuclear energy? Heat?) Perhaps the definition could be revised as follows?:

> An Artifact Function that is realized in processes in which an Artifact is reacted with other substances in order to release chemical or nuclear energy to be used for heat or for work.

**Comment by neilotte** [comment]
@gregfowlerphd @cameronmore It appears the original definition was poorly derived from https://en.wikipedia.org/wiki/Fuel#:~:text=A%20fuel%20is%20any%20material,to%20be%20used%20for%20work. 

Here, it was clear that the Artifact that is reacting with other substances is a portion of fuel and not just some artifact.  

Hence, the definition should read: 

> An Artifact Function that is realized in processes in which a Portion of Fuel is reacted with other substances in order to release chemical or nuclear energy to be used for heat or for work.


That said, cco:PortionOfFuel is presently defined as "A Portion of Material that is designed to be used as an input in a Combustion process", which is too narrow to include nuclear energy which is produced through fission reactions. 

Therefore, I propose updating the definition of Fuel Artifact Function as above and the definition of Portion of Fuel along the lines of the original wikipedia article, which references only the production of thermal energy rather than the particular form of the reaction process for getting there.
