### ISSUE TITLE
Cannot parse allcore.ttl file

### ISSUE THREAD

**Issue by Fbhare** [CommonCoreOntology/CommonCoreOntologies#40]
Receiving the following error when trying to open the allcore file in Protege: org.semanticweb.owlapi.rdf.rdfxml.parser.RDFParserException: [line=8:column=17] Expecting rdf:RDF element.

What to do?

Thank you!

**Comment by mark-jensen** [comment]
I'm not seeing any problems on my side. Can you provide more specifics, such as: What version of Protege are you using? Can you open All Core in a text editor and tell me what version number/date is listed? How did you get the files, clone the repo or download a compressed file?

**Comment by rorudn** [comment]
Another specific that would help is to send us your catalog.xml file. It should be in the folder from which you are loading the ontology files.

**Comment by APCox** [comment]
If you're seeing that error in Protege and trying to troubleshoot based on its feedback, be sure to select the correct file format from the options at the top of the error window or you won't get a useful message. Since you say the problem is with AllCoreOntology.ttl, selecting either '(4) Turtle' or '(15) Turtle Syntax' as the format is your best bet.

I created a parsing error by deleting the period at the end of a class assertion block on line 29 of a ttl file. Here are the relevant error messages:
![image002](https://user-images.githubusercontent.com/33437521/57548367-bee6d700-732e-11e9-9f55-b0dfdfea0b39.png)
and
![image001](https://user-images.githubusercontent.com/33437521/57548392-cd34f300-732e-11e9-9193-52dafd823751.png)

Unfortunately these error messages typically only point you to the approximate location of the issue. I caused the error by deleting a '.' at the end of line 29. The first message tells me a '.' was expected on line 28 and the second tells me a '.' was expected at line 33 column 33. So it's useful but you'll need to understand the syntax in order to identify the issue (assuming it's in the ontology file).

**Comment by Fbhare** [comment]
Thank you all for the pointers.

I am using Protege 5.5 (the latest)
and the most recent allcoreontology.ttl file from GitHub.

Screen shots with the turtle and turtle syntax errors attached.  I had renamed it to “v2” since I downloaded twice, but got same error with both.

**Comment by APCox** [comment]
I don't see any attachments, here or in the email version. Perhaps try again.

**Comment by Fbhare** [comment]
By the way, I am only having this problem with this specific allcore file.  I have been using one from last fall, but I wanted to make sure I had the latest version as a reference.


<img width="951" alt="Screen Shot 2019-05-10 at 18 37 08" src="https://user-images.githubusercontent.com/50471158/57574242-70573c80-7403-11e9-9641-925e9f8b69fe.png">
<img width="972" alt="Screen Shot 2019-05-10 at 18 37 33" src="https://user-images.githubusercontent.com/50471158/57574243-70573c80-7403-11e9-95e8-c4fdc4bcb089.png">

**Comment by APCox** [comment]
I do not see anything wrong with the posted AllCoreOntology.ttl file either. I also downloaded the entire repo to another computer and opened All Core to test. Everything worked as expected.

Please note that the only thing the All Core Ontology does is to aggregate the Common Core Ontologies for easier loading/viewing/importing. It does not add any content to the CCO. So, as long as the previous version you have imports the Agent, Artifact, Event, Quality, and Units of Measure ontologies (which I believe it does), you have everything you need.

Nonetheless, I'm curious as to why you're getting this error -- especially since you said you downloaded it twice.

**Comment by mark-jensen** [comment]
@Fbhare I've tried fresh pulls of the repo, both on Mac or PC, and using different versions of Protege. No luck duplicating this error.

Please try this-
Download a fresh archive of the repository, extract all contents to a new directory, and then try to open All Core again. Do NOT copy any old files into that new directory. 

Does that fail with the same error?
If so, try to open just the Extended Relation Ontology. 
If that works, try opening the Agent Ontology.

**Comment by rorudn** [comment]
@Fbhare please contact us directly if you continue to have this problem, we'll be glad to help get you up and running.
