### ISSUE TITLE
artefacts should be disjoint

### ISSUE THREAD

**Issue by RdR1024** [CommonCoreOntology/CommonCoreOntologies#41]
Artefacts like clothing and combustion chamber are not currently declared disjoint, but should be.
A piece of clothing is designed to be a _piece of clothing_ and not designed to be a _combustion chamber_.  Therefore, with the exception of a rare class that might conceivably be designed to be both, these universals are disjoint.  
For the exception of "joint function" classes, I suggest the better option is to specifically assert a joint function class.  For example, artifacts exist that are both chair and stepladder.  However, rather than asserting that the universal _chair_ overlaps with the universal _stepladder_ , it would be clearer (i.e. closer to the normal use of the terms) to keep those universals disjoint, and create a special universal for _stepladder-chair_ which represents the exceptional combination.

**Comment by rorudn** [comment]
I read a news story about a school district in Newark NJ that made use of a water tower as a gymnasium. Human ingenuity being what it is, I'd tread lightly in adding disjoint axioms between classes of artifacts. I'd also remind you of the lessons of data warehousing where the design of the warehouse dictated to the data users what was and was not of importance. My view is that the more axioms you place into an ontology the more chance you have of getting it wrong and the more rigid your model becomes. 

Keep in mind too that not everyone that uses the Common Core Ontologies stores data in RDF and among those that do not all use OWL reasoners. These groups use different methods for checking their data for issues. We can't really afford to create the content needed for all these different methods.  So in response to the main point, I don't think that the CCO should have disjoint axioms between all the pairs of artifact classes that are thought to be mutually exclusive.  I understand that this does put the burden on users to implement their own ways of enforcing constraints. In your case you'd need to add the axioms to a file that imports the Artifact Ontology or the All Core Ontology.

To address at least one of your secondary  issues, the CCO has a way of characterizing the design of artifacts using Artifact Models. We find this to be a good way to both demarcate designed functions from off-label (improvised) functions and to distinguish designed performance from actual performance (due to flaws in manufacturing or damage or wear). Using it will obviate the need to create classes of combined functions.

**Comment by cameronmore** [comment]
Members of the community have recently done work which adds to the semantics at work here [arxiv paper here](https://arxiv.org/abs/2405.00183) (@johnbeve may correct anything I misrepresent)

In sum: while an artifact may be designed to perform one function, it may have a disposition to do many things. When an agent, a human, uses an artifact for something besides its designed function, we may call this a 'capability'. A blanket may be designed to provide warmth (function) but because of other dispositions it has (its thickness, its color), it may be used to block out light from coming in the window--hence a capability is created.

Also, I'm thinking that depending what level of granularity we are looking at, it may be difficult to distinguish functions from each other or to say where one artifact class ends and another begins. Stools, chairs, and benches all seem to have the same function but are designed according to roughly different styles.

Another case seems to be when an artifact loses its function but retains other 'functional' dispositions, like an escalator that 'breaks' and 'becomes' stairs. (comedian Mitch Hedberg talks about [this](https://www.youtube.com/watch?v=tqOkWWV6a_U)). When a massage chair breaks, is it now just a regular chair? When a heated blanket breaks, doesn't it still retain its disposition to perform some of its function (of warming) even if part of it broke? These are complex questions.

I hope this proposed term and semantics addresses this problem.

**Comment by neilotte** [comment]
[RdR1024](https://github.com/RdR1024) -- I am closing this ticket with the recommendation that this discussion be moved to the discussion section and cite this ticket. Because some artifacts may be reasonably considered disjoint while others are not--and because there will clearly be debate around some of these relations--this means there is considerable research and discussion task required in order to execute any change resulting from this recommendation.
