### ISSUE TITLE
Define subnational entity

### ISSUE THREAD

**Issue by neilotte** [CommonCoreOntology/CommonCoreOntologies#43]
There is a class 'subnational entity identifier' that is defined as identifying a subnational entity, but subnational entity is undefined. It appears to be a geospatial region located inside a country--but does this include, for instance, the territories occupied by the country?

**Comment by mark-jensen** [comment]
The term appears to be used for grouping identifiers of geopolitical entities that are not countries, but part of a country (ie, national vs sub-national). Thus, identifiers for city, county, village, hamlet, province, etc., all should be considered as sub-national identifiers. 


> It appears to be a geospatial region located inside a country--but does this include, for instance, the territories occupied by the country?

I am not sure I understand. Can you give an example of a territory that a country occupies?

Your question points out a disparity between the sub-typing of geopolitical entities and their identifiers. I think we can do some work here to improve that. I also think the definition for subnational entity should be changed.

**Comment by mark-jensen** [comment]
>It appears to be a geospatial region located inside a country--but does this include, for instance, the territories occupied by the country?

Can you give an example of a territory that a country occupies?

Your question points out a disparity between the sub-typing of geopolitical entities and their identifiers. I think we can do some work here to improve that. However, the identifiers are just defined classed that may be of help in particular applications and (ideally) shouldn't be instantiated directly.

Defining a grouping term for any "proper" (ie, not fiat) geopolitical entity which is part of a country may be helpful. The term would essentially group any administrative division of a country or one of its divisions. However, use of 'nation' or 'national' can be confusing given that 'nation' and 'country' are not technically synonymous. 

'Country Administration Region' = A Geopolitical Entity that is part of a Country and an administrative division of some Geopolitical Entity which is part of that Country.

Since a country is necessarily part of itself, this handles the case of first order divisions like states and provinces.

**Comment by neilotte** [comment]
To the clearer: 

I think 'sub-national' is intended to be a shorter alternative label for 'First Order Adminstrative Region'. Perhaps for this reason, presently, 'Sub-National Entity Identifier' is equivalent to 'designates some coco:FirstOrderAdministrativeRegion. 

However, cities are not first order administrative regions in the US. Hence, the city identifier 'New York City' does not designate a first order administrative region. 

https://en.wikipedia.org/wiki/List_of_administrative_divisions_by_country

**Comment by mark-jensen** [comment]
>I think 'sub-national' is intended to be a shorter alternative label for 'First Order Adminstrative Region'.

It's subtypes don't indicate that though, city and county are included, which are not first order.

I believe we are going to delete Sub-National Entity Identifier and its subclasses. As well as some others in the geopolitical identifier branch. They are not needed and potentially lead to confusion. Use of 'national' in particular is a problem. 

Does First Order Administrative Region cover what you need, or do you need a term like proposed above, ie. for any geopolitical division of a country or one of its parts?

**Comment by mark-jensen** [comment]
@neilotte I just realized you may not have pulled the most current version of the ontology. The axiom you are referring to was deleted.
