### ISSUE TITLE
The Ontology URLs are returning request information

### ISSUE THREAD

**Issue by tonicebrian** [CommonCoreOntology/CommonCoreOntologies#55]
I can't load CCO ontologies in Protege. I've realised that it is because malformed content returned.

When issuing:
```
 $ curl -s http://www.ontologyrepository.com/CommonCoreOntologies/Mid/InformationEntityOntology | head -n 20
```

this is the output I retrieve:

```
KH: CHECKING HEADERS!</br>Array
(
    [X-Forwarded-For] => 46.26.120.69
    [X-Forwarded-Proto] => http
    [X-Forwarded-Port] => 80
    [Host] => www.ontologyrepository.com
    [X-Amzn-Trace-Id] => Root=1-5d777430-ddba82a9e92da43d69944636
    [User-Agent] => curl/7.54.0
    [Accept] => */*
)
</br>KH: CHECKING HEADERS DONE!</br><html><div class="container"><pre><meta http-equiv="content-type" content="text/html; charset=UTF-8">@prefix : &lthttp://www.ontologyrepository.com/CommonCoreOntologies/Mid/InformationEntityOntology/&gt .
@prefix cco: &lthttp://www.ontologyrepository.com/CommonCoreOntologies/&gt .
@prefix obo: &lthttp://purl.obolibrary.org/obo/&gt .
@prefix owl: &lthttp://www.w3.org/2002/07/owl#&gt .
@prefix rdf: &lthttp://www.w3.org/1999/02/22-rdf-syntax-ns#&gt .
@prefix xml: &lthttp://www.w3.org/XML/1998/namespace&gt .
@prefix xsd: &lthttp://www.w3.org/2001/XMLSchema#&gt .
@prefix rdfs: &lthttp://www.w3.org/2000/01/rdf-schema#&gt .
@base &lthttp://www.ontologyrepository.com/CommonCoreOntologies/Mid/InformationEntityOntology&gt .
```

First section is not TTL but something related to the HTTP request.

**Comment by mark-jensen** [comment]
@tonicebrian Sorry about that! It’s an artifact of some testing we’ve been doing while updating our servers. Will fix ASAP.

**Comment by lonniev** [comment]
As of today (27 Nov 2019), when I try to HTTP GET those ontologyrepository.com Mid ontologies, I am getting server-side HTTP 500 responses.

Is the server healthy?

**Comment by lonniev** [comment]
Apparently, according to Chrome's DevTools, the document is getting returned and then it is a followup call for the favicon that is throwing the HTTP 500 error.

GET http://www.ontologyrepository.com/favicon.ico 500 (Internal Server Error)

I think, too, that the OWL or Turtle file is getting sent back with the URL lt gt symbols escaped. The raw response for the page shows the characters as &lt; and &gt; and that is right where the OWL parsers I am using complain about the @prefix syntax.

Can't be sure since I'm not having luck sending a request with different Accept headers to see if I can get the server's REST handler to return the ontology file in other formats.

**Comment by rorudn** [comment]
Thanks for this and apologies for the difficulties you're experiencing. We'll sort it out and post when fixed.

**Comment by rorudn** [comment]
The situation is improved. In our testing we're finding that HTTP calls now succeed in downloading files without escaped text. Other types of access is more sporadic. For example opening the AllCoreOntology in Protege succeeds while opening the Artifact Ontology fails. Access to any of the ontologies using ROBOT is successful in about 1 out of 5 attempts. We will continue to work on the problems but receiving feedback from others on their results will be appreciated.

**Comment by tonicebrian** [comment]
For me it works also 👍
