### ISSUE TITLE
Group of Persons, Agent, Person

### ISSUE THREAD

**Issue by nklsbckmnn** [CommonCoreOntology/CommonCoreOntologies#57]
Is every _Person_ an _Agent_? Regardless of cognitive development? If not, why is _Group of Persons_ a subclass of _Group of Agents_? Shouldn't there be groups containing also _Persons_ who are not _Agents_?

_Person_ has alternative label "human". From which point on is an _Organism_ a _Person_/human? Are there _Persons_/humans before birth or maybe even before nidation?

**Comment by mark-jensen** [comment]
We don't make any commitment as to when in the developmental process a human comes into existence. I understand there is a sense of 'person' that invokes the notions of agency and legal status, and perhaps the deeper existential question as well, but our definition makes it clear (I hope) that CCO Person does touch on those things. In CCO a Person, aka human, is just that, a member of the species, so defined, as current understanding dictates.

We use the term Agent simply to classify things which are intentionally active and causal participants in processes. Agents are things that perform intentional acts. We don't offer a formal treatment of intentionality and thus it can be regarded as primitive. 

I agree that Group of Persons shouldn't be explicitly asserted as a sub of Group of Agents. Will update that for next release.

**Comment by eliasweatherfield** [comment]
Thanks for the helpful reply.

I would submit that _Organization_ shouldn't be subclassed under _Group of Agents_ either. There seem to be examples of members of organizations where it's not clear that they must be agents. For example, a newborn could become shareholder (and thus member of a public corporation?) by inheriting shares.

**Comment by jonathanvajda** [comment]
I suggest that in addition to the reasons given above, the term 'person' could follow BFO design principles more closely.

'person' is defined as "an animal that is a member of homo sapiens". But 'corporate person' (a legal status, as Mark mentioned) would intuitively be a subclass of 'person' and it would not be a subclass of 'animal'. I realize corporate personhood is contentious, but the term is codified in this way in various laws (US and perhaps elsewhere). It may matter in the industrial ontology foundry, for example, and so we should be sensitive to future-proofing. I don't have an interest in debating the possibility of sentient AI, immaterial angels, God, etc. that might also be counter-examples.

If 'person' just is an animal that is a member of _homo sapiens_ and if 'person' often evokes such connotations of agency or legal status, why isn't the term just 'Human' or 'Human Person'? After all, whatever debates about when a human comes into existence (embryologists could tell us), if the class is to pick out humans and only humans irrespective of 'personhood debates', why not just avoid this minefield and go with 'human'?

**Comment by neilotte** [comment]
Addressed in 1.5.
