### ISSUE TITLE
Should one use a modal relation to represent that a Role is realized in some Process?

### ISSUE THREAD

**Issue by eliasweatherfield** [CommonCoreOntology/CommonCoreOntologies#73]
I was wondering when, if ever, it would make sense to choose the modal version of the realizes relation to represent that a Role is realized in some Process. Any thoughts?

**Comment by neilotte** [comment]
@eliasweatherfield -- If one wanted to talk about the way in which some role-bearing thing should, could, or would participate in a process, then it may make sense to have a modally-realized role. 

For instance: "The wedding plan says Sally will officiate and John will usher" could assert that Sally bears an officiate role and John bears an usher role and both roles are modally realized in a modal Wedding Process. 

Alternatively, one could say there are two process parts of the modal wedding process--a modal act of officiating and a modal act of ushering--and Sally and John are both 'agent_in' these respective roles. This treatment forgoes roles entirely.

**Comment by eliasweatherfield** [comment]
Thanks for the reply.

As I understand it, we use modal relations because there can be e. g. a directive information entity that prescribes an entity that may never actually exist.

But if I'm not mistaken, roles (and dispositions) can also exist without ever actually being realized. Is that in itself not sufficient to justify using a modal version of "realized by"?

(I guess in both cases one could use universal instead of existential quantification?)

**Comment by eliasweatherfield** [comment]
What I meant was: Why only use modal relations for things that are prescribed. Why not also for things that are possible or fictional.

**Comment by mark-jensen** [comment]
@eliasweatherfield Use of MRO properties can be used for modeling predictions or hypotheses. I am not sure about fictional entities, I haven't thought about it. 

Representing that a role or disposition can possibly be realized is implicit given the nature of realizables and the inheres/bears relationship. If some entity bears a realizable, then it's possible they may realize it at some point, given the correct triggering conditions within a process of the right type. There is no need to assert anything more. Realizables by their nature imply capacity, tendency, possibility, e.g., a behavior given certain conditions. Suga'rs tendency to dissolve in water. 

The key is that use of MRO is for making assertions that only link non-existent entities. A real person actually bears existing dispositions or roles which actually get realized in processes sometimes, or maybe never. One only needs to assert that the person bear the realizable to know they could realize it. (admittedly there is a case where some other feature of the person blocks the realization, but that isn't relevant here)
As @neilotte points out, if you want to model the way in which some role or disposition might or should get realized then use MRO for the non-extant entities. That is because the process which realizes the role that is described in a plan or prediction doesn't exist given the context of the data being modeled. If later, new data about an actual process that occurred (time and place) exists, then we know there was an actual realizing process and you would use the standard non-MRO properties. 

> person cco:bears role
> person cco:designated-by name
> plan mro:prescribes planned-act
> planned-act mro:realizes role
> planned-act mro:occurs-on planned-duration
> plan cco:prescribes actual-act
> actual-act cco:realizes role
> actual-act cco:occurs-on measured-duration

**Comment by eliasweatherfield** [comment]
That answers my question, thank you.
