### ISSUE TITLE
Getting the other ontologies

### ISSUE THREAD

**Issue by richylyq** [CommonCoreOntology/CommonCoreOntologies#74]
Hi,

Where will I be able to get the ontologies for
```
Aircraft Ontology

Airforce Aircraft Maintenance Ontology

Army Universal Task List Ontology
```

**Comment by rorudn** [comment]
Hi,
The extension ontologies were developed under government contract. Sharing requires approval from the gov't sponsor. This is easiest if your work is also a government project rather than commercial but even then it can be done. Please use the "contact us" link at the bottom of this page: https://www.cubrc.org/index.php/data-science-and-information-fusion/ontology to send an email describing your interest in more detail.
