### ISSUE TITLE
Request for a User Role class

### ISSUE THREAD

**Issue by aellenhicks-jhuapl** [CommonCoreOntology/CommonCoreOntologies#77]
We have need of a User Role class. Here is a proposed definition. 

"A role that inheres in an agent by virtue of that agent being mentioned in a plan for the use of some material entity or being part of a target audience mentioned in such a plan."

**Comment by rorudn** [comment]
I'd want to first investigate whether this need can be accomplished using a defined class based on classes and properties already present. A first try: If a plan specifies that a group of persons will use some material entity then the plan would specify the performance of acts of artifact employment with members of that group as agents and instances of the material entity as object. 

The motive behind the push back is that equating use with roles stands that chance of trivializing roles. If I plan a party and with a sub-plan to rent chairs in order to accommodate my guests I don't see that I've bestowed a role upon them, at least not in a manner that satisfies the definition: 

"b is a role means: b is a realizable entity & b exists because there is some single bearer that is in some special physical, social, or institutional set of circumstances in which this bearer does not have to be& b is not such that, if it ceases to exist, then the physical make-up of the bearer is thereby changed."

In my reading of this definition "special" stands out. 

Also, there's the nuance that i'm sure you didn't mention to keep the request simple, but if we did implement this class the role would inhere in the modal relation ontology namespace only.

**Comment by aellenhicks-jhuapl** [comment]
I see your point about "special", but I also must confess, I don't where to draw the boundary between what is "special" and what is not "special". Do you have any insights here? This is not a CCO class, so I understand if the answer is simply "I know special when I see it." But if you have insights I lack, I'd appreciate it.

**Comment by rorudn** [comment]
Not really but being foolhardy I offer the following rules of thumb in the spirit of camaraderie among BFOers. I think that the bearer of a role ought to have consented to adopt it and have the option to shed it. I think that the event that creates the role should be part of the economic, political, military or legal system.

**Comment by aellenhicks-jhuapl** [comment]
Thanks. I think it’s a good rule of thumb.
